const sent = [
  { marathi: "मला पुस्तक वाचायला आवडते", english: "I like to read books" },
  { marathi: "आज हवामान छान आहे", english: "The weather is nice today" },
  { marathi: "तुमचे नाव काय आहे?", english: "What is your name?" },
  { marathi: "तुम्ही कुठे राहता?", english: "Where do you live?" },
  { marathi: "माझे नाव स्वप्निल आहे", english: "My name is Swapnil" },
  { marathi: "मी ठीक आहे", english: "I am fine" },
  { marathi: "तुमचे कसे चालले आहे?", english: "How are you doing?" },
  { marathi: "मी पुण्यात राहतो", english: "I live in Pune" },
  { marathi: "तुम्हाला चहा आवडतो का?", english: "Do you like tea?" },
  { marathi: "हो, मला चहा आवडतो", english: "Yes, I like tea" },
  { marathi: "कृपया मला मदत करा", english: "Please help me" },
  { marathi: "धन्यवाद", english: "Thank you" },
  {
    marathi: "उद्याच्या बैठकीची वेळ काय आहे?",
    english: "What is the timing of tomorrow's meeting?",
  },
  { marathi: "मी कामात व्यस्त आहे", english: "I am busy with work" },
  { marathi: "हे खूप सुंदर आहे", english: "This is very beautiful" },
  { marathi: "कृपया पुन्हा सांगा", english: "Please say it again" },
  { marathi: "माझ्याकडे वेळ नाही", english: "I don’t have time" },
  { marathi: "तुम्हाला कशाची गरज आहे?", english: "What do you need?" },
  { marathi: "मला थोडी विश्रांती घ्यायला हवी", english: "I need some rest" },
  { marathi: "हे किती किंमती आहे?", english: "How much does this cost?" },
  { marathi: "तुम्ही कुठे जात आहात?", english: "Where are you going?" },
  { marathi: "मी ऑफिसला चाललो आहे", english: "I am going to the office" },
  { marathi: "आपण भेटू शकतो का?", english: "Can we meet?" },
  { marathi: "मी प्रवासासाठी तयार आहे", english: "I am ready for the trip" },
  { marathi: "मी तुला विसरलो नाही", english: "I did not forget you" },
  { marathi: "ही जागा खूप सुंदर आहे", english: "This place is very beautiful" },
  {
    marathi: "माझ्या मित्राला भेटायचे आहे",
    english: "I want to meet my friend",
  },
  {
    marathi: "तुमच्याशी बोलून आनंद झाला",
    english: "It was nice talking to you",
  },
  { marathi: "माझ्या घरी चला", english: "Come to my home" },
  { marathi: "तुम्हाला हे आवडेल का?", english: "Would you like this?" },
  { marathi: "आज जेवण खूप चांगले होते", english: "Today's food was very good" },
  { marathi: "मी तुला मदत करू शकतो", english: "I can help you" },
  { marathi: "कृपया माझ्यासाठी थांबा", english: "Please wait for me" },
  {
    marathi: "तुम्ही कोणता चित्रपट पाहिला?",
    english: "Which movie did you watch?",
  },
  {
    marathi: "माझी परीक्षा पुढच्या आठवड्यात आहे",
    english: "My exam is next week",
  },
  { marathi: "मी लवकरच परत येईन", english: "I will be back soon" },
  {
    marathi: "हे माझ्यासाठी खूप महत्त्वाचे आहे",
    english: "This is very important for me",
  },
  { marathi: "तुम्ही मराठी बोलता का?", english: "Do you speak Marathi?" },
  { marathi: "हो, मला मराठी बोलता येते", english: "Yes, I can speak Marathi" },
  {
    marathi: "तुम्हाला इंग्रजी समजते का?",
    english: "Do you understand English?",
  },
  { marathi: "मी थोडी इंग्रजी बोलतो", english: "I speak a little English" },
  { marathi: "कृपया मला मार्ग दाखवा", english: "Please show me the way" },
  { marathi: "मी नवीन पुस्तक विकत घेतले", english: "I bought a new book" },
  { marathi: "हे गाणे खूप छान आहे", english: "This song is very nice" },
  { marathi: "तुम्ही मला फोन करू शकता", english: "You can call me" },
  { marathi: "मी घरी आहे", english: "I am at home" },
  { marathi: "माझ्याकडे नवीन कल्पना आहे", english: "I have a new idea" },
  { marathi: "मी काम पूर्ण केले", english: "I finished the work" },
  { marathi: "तुमच्या मदतीसाठी धन्यवाद", english: "Thank you for your help" },
  { marathi: "हे माझ्यासाठी सोपे आहे", english: "This is easy for me" },
  { marathi: "हे आपल्यासाठी चांगले आहे", english: "This is good for you" },
  { marathi: "तुम्ही कधीपर्यंत येणार?", english: "When will you come?" },
  { marathi: "मला अभ्यास करायचा आहे", english: "I need to study" },
  {
    marathi: "तुमच्या मित्रांना भेटायला आवडेल",
    english: "I would love to meet your friends",
  },
  {
    marathi: "तुम्ही सकाळी किती वाजता उठता?",
    english: "What time do you wake up in the morning?",
  },
  { marathi: "तुम्हाला कोणता रंग आवडतो?", english: "Which color do you like?" },
  { marathi: "माझा आवडता रंग निळा आहे", english: "My favorite color is blue" },
  { marathi: "आज सुट्टी आहे का?", english: "Is it a holiday today?" },
  { marathi: "माझ्याकडे एक नवीन कल्पना आहे", english: "I have a new idea" },
  { marathi: "हे खूप कठीण आहे", english: "This is very difficult" },
  { marathi: "माझे काम पूर्ण झाले", english: "My work is finished" },
  { marathi: "हे कसे करायचे?", english: "How to do this?" },
  { marathi: "मी आता व्यस्त आहे", english: "I am busy right now" },
  { marathi: "आपण भेटू शकतो का?", english: "Can we meet?" },
  {
    marathi: "मी उद्या ऑफिसला जाणार आहे",
    english: "I am going to the office tomorrow",
  },
  { marathi: "तुम्हाला आवडले का?", english: "Did you like it?" },
  { marathi: "हो, मला खूप आवडले", english: "Yes, I liked it a lot" },
  {
    marathi: "तुमच्या शहराचे नाव काय आहे?",
    english: "What is the name of your city?",
  },
  { marathi: "मी संगीत ऐकतो", english: "I listen to music" },
  { marathi: "माझ्याकडे एक योजना आहे", english: "I have a plan" },
];

export default sent;
